def call(action, Map params = [:]) {
    switch(action) {
        case 'feishu':
            feishu(params)
            break
        case 'email':
            email(params)
            break
        case 'all':
            feishu(params)
            email(params)
            break
        default:
            echo "Unknown notification action: ${action}"
    }
}

def feishu(Map params) {
    def title   = params.title   ?: "Build #${BUILD_NUMBER}"
    def message = params.message ?: ''
    def link    = params.link    ?: env.BUILD_URL
    def color   = params.color   ?: 'green'

    sh """
        scripts/notify-feishu.sh \\
            --title '${title}' \\
            --message '${message}' \\
            --link '${link}' \\
            --color '${color}'
    """
}

def email(Map params) {
    def subject = params.subject ?: "Build #${BUILD_NUMBER} Report"
    def body    = params.body    ?: 'See Jenkins for details.'
    def to      = params.to      ?: 'team@example.com'

    mail(
        to: to,
        subject: subject,
        body: body,
        mimeType: 'text/html'
    )
}

def nightlySummary(failedPlatforms, buildConfig) {
    def resultIcon = currentBuild.result == 'SUCCESS' ? '✅' : '❌'
    def title = "${resultIcon} Nightly Build #${BUILD_NUMBER}"
    def msg = """
Config: ${buildConfig}
Result: ${currentBuild.result}
Failed Platforms: ${failedPlatforms ? failedPlatforms.join(', ') : 'None'}
"""

    feishu(
        title: title,
        message: msg,
        link: "${env.BUILD_URL}/allure-report",
        color: currentBuild.result == 'SUCCESS' ? 'green' : 'red'
    )

    email(
        subject: "[chaos-nightly] ${currentBuild.result} Build #${BUILD_NUMBER}",
        body: """
<h2>${title}</h2>
<p>Config: <strong>${buildConfig}</strong></p>
<p>Test Report: <a href="${env.BUILD_URL}/allure-report">Allure Report</a></p>
<p>Daily Report: <a href="${env.BUILD_URL}/daily-report">Daily Report</a></p>
<p>SonarQube: <a href="${env.SONAR_HOST_URL}/dashboard?id=chaos-il2cpp">${env.SONAR_HOST_URL}</a></p>
<hr>
<p>Generated by Jenkins Build #${BUILD_NUMBER}</p>
""",
        to: 'team@example.com'
    )
}
