#!/bin/bash
# build-html-daily.sh — Generate 3-in-1 HTML daily report
# Combines build status + Allure test summary + SonarQube quality gate
# Usage: build-html-daily.sh <artifacts_dir> <build_number> <build_config>

set -euo pipefail

ARTIFACTS_DIR="${1:?Missing artifacts dir}"
BUILD_NUM="${2:?Missing build number}"
BUILD_CONFIG="${3:?Missing build config}"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
DATE_TAG=$(date '+%Y%m%d')
REPORT_FILE="${ARTIFACTS_DIR}/daily-report-${DATE_TAG}.html"

# Gather test results from Allure if available
ALLURE_SUMMARY="${ARTIFACTS_DIR}/allure-report/widgets/summary.json"
TEST_PASSED="N/A"
TEST_FAILED="N/A"
TEST_SKIPPED="N/A"

if [[ -f "$ALLURE_SUMMARY" ]]; then
    TEST_PASSED=$(jq -r '.statistic.passed // 0' "$ALLURE_SUMMARY")
    TEST_FAILED=$(jq -r '.statistic.failed // 0' "$ALLURE_SUMMARY")
    TEST_SKIPPED=$(jq -r '.statistic.skipped // 0' "$ALLURE_SUMMARY")
fi

# Gather SonarQube quality gate status (from API result file if available)
SONAR_STATUS="N/A"
SONAR_FILE="${ARTIFACTS_DIR}/sonar-qualitygate.json"
if [[ -f "$SONAR_FILE" ]]; then
    SONAR_STATUS=$(jq -r '.projectStatus.status // "UNKNOWN"' "$SONAR_FILE")
fi

# Build status
BUILD_STATUS="SUCCESS"
if [[ -f "${ARTIFACTS_DIR}/build-summary.json" ]]; then
    BUILD_STATUS=$(jq -r '.result // "UNKNOWN"' "${ARTIFACTS_DIR}/build-summary.json")
fi

# HTML generation
cat > "$REPORT_FILE" << REPORTEOF
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Report #${BUILD_NUM} — ${DATE_TAG}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: #f0f2f5; color: #333; padding: 20px; }
        .header { background: linear-gradient(135deg, #1a1a2e, #16213e); color: #fff;
                  padding: 30px; border-radius: 8px; margin-bottom: 20px; }
        .header h1 { font-size: 1.5rem; margin-bottom: 8px; }
        .header .meta { opacity: 0.8; font-size: 0.9rem; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; margin-bottom: 20px; }
        .card { background: #fff; border-radius: 8px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .card h2 { font-size: 1rem; color: #666; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .card .value { font-size: 2rem; font-weight: 700; }
        .status-pass { color: #10b981; }
        .status-fail { color: #ef4444; }
        .status-warn { color: #f59e0b; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background: #f9fafb; font-weight: 600; font-size: 0.85rem; color: #666; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8rem; font-weight: 600; }
        .badge-pass { background: #d4edda; color: #155724; }
        .badge-fail { background: #f8d7da; color: #721c24; }
        .links { margin-top: 20px; }
        .links a { display: inline-block; margin-right: 12px; color: #4361ee; text-decoration: none; font-weight: 500; }
        .links a:hover { text-decoration: underline; }
        hr { border: none; border-top: 1px solid #e5e7eb; margin: 20px 0; }
        .footer { text-align: center; color: #999; font-size: 0.8rem; }
    </style>
</head>
<body>
    <div class="header">
        <h1>chaos-il2cpp Daily Report — ${DATE_TAG}</h1>
        <div class="meta">
            Build #${BUILD_NUM} · ${BUILD_CONFIG} · ${TIMESTAMP}
        </div>
    </div>

    <div class="grid">
        <div class="card">
            <h2>构建状态</h2>
            <div class="value ${BUILD_STATUS}">${BUILD_STATUS}</div>
        </div>
        <div class="card">
            <h2>测试通过</h2>
            <div class="value status-pass">${TEST_PASSED}</div>
        </div>
        <div class="card">
            <h2>测试失败</h2>
            <div class="value status-fail">${TEST_FAILED}</div>
        </div>
        <div class="card">
            <h2>跳过</h2>
            <div class="value status-warn">${TEST_SKIPPED}</div>
        </div>
    </div>

    <div class="card">
        <h2>SonarQube 质量门禁</h2>
        <div class="value ${SONAR_STATUS}">${SONAR_STATUS}</div>
    </div>

    <div class="links">
        <a href="allure-report/index.html">查看 Allure 测试报告 →</a>
        <a href="/sonar/dashboard?id=chaos-il2cpp">查看 SonarQube →</a>
        <a href="build-summary.html">构建摘要 →</a>
    </div>

    <hr>
    <div class="footer">
        <p>Generated by chaos-il2cpp Nightly Pipeline · Jenkins + Allure + SonarQube</p>
    </div>
</body>
</html>
REPORTEOF

echo "Daily report generated: ${REPORT_FILE}"
